export const SET_PREVIEW_IMG = 'SET_PREVIEW_IMG';
export const REMOVE_PREVIEW_IMG = 'REMOVE_PREVIEW_IMG';
export const SET_FIRST_PREVIEW_IMG = 'SET_FIRST_PREVIEW_IMG';

export const TOGGLE_VARIANTS_FORM = 'TOGGLE_VARIANTS_FORM';

export const ADD_VARIANT_VALUE = 'ADD_VARIANT_VALUE';
export const ADD_VARIANT_KEY = 'ADD_VARIANT_KEY';
export const REMOVE_VARIANT_VALUE = 'REMOVE_VARIANT_VALUE';

//form
export const RESET_VARIANT_VALUE = 'RESET_VARIANT_VALUE';

//variants

export const INITIAL_VARIANT_VALUE = 'INITIAL_VARIANT_VALUE';
export const SET_VARIANT_CB = 'SET_VARIANT_CB';
export const SET_VARIANT_PRICE = 'SET_VARIANT_PRICE';
export const SET_VARIANT_SKU = 'SET_VARIANT_SKU';
export const SET_VARIANT_BARCODE = 'SET_VARIANT_BARCODE';
